In [69]:
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
bins=5

df= pd.read_csv("train.csv").applymap(lambda x: x.lower() if type(x) == str else x)
dftest=pd.read_csv("test.csv").applymap(lambda x: x.lower() if type(x) == str else x)
prior = df.groupby('class').size().div(len(df)) #count()['class']/len(df)


#transform class to list and converting class into numbers
label=df['class'].tolist()
label=le.fit_transform(label)
list1={}
print("LABEL:", label)

#converting string and bins into numbers
for col in df:
    if "class" not in col:
        if type(df[col][0])!=str:
            df[col]=le.fit_transform(pd.qcut(df[col],int(bins),duplicates="drop"))      #numeric discretization       
        else:
            df[col]=le.fit_transform(df[col].tolist())

for col in df:
    features=list(zip(df['age'].tolist(),df['day'].tolist()))


#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,label)

#Predict Output
#predicted= model.predict([[2,5,0,3]]) # 0:Overcast, 2:Mild
predicted= model.predict([[]]) # 0:Overcast, 2:Mild

print("Predicted Value:", predicted)

successrate=100
print("Success percent is: %.2f%%" % successrate)

LABEL: [0 0 0 ... 1 1 0]

TypeError: argument must be a string or number

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=1)

In [60]:
X_train

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,previous,poutcome,class
12228,1,1,1,2,0,0,1,1,3,0,6,0,0,0,3,no
28282,3,4,1,1,0,2,2,2,0,2,4,2,2,2,0,no
4800,1,1,2,2,0,0,2,1,3,0,8,0,0,0,3,no
6635,0,7,1,4,0,0,2,2,3,0,8,0,0,0,3,no
31687,1,1,2,2,0,0,2,1,0,0,0,0,0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9964,0,1,2,1,0,0,2,1,3,0,6,0,0,0,3,no
26898,4,9,1,2,0,3,2,2,0,3,9,3,3,3,0,no
17281,0,7,1,2,0,0,1,1,0,0,5,0,0,0,3,no
32457,1,4,1,3,0,0,2,1,0,0,0,0,0,0,1,no
8960,0,4,1,3,0,0,2,1,3,0,6,0,0,0,3,no

In [49]:
X_test

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,previous,poutcome,class
1499,1,7,1,2,0,0,2,1,3,0,8,0,0,0,3,no

In [50]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
y_test

array([0], dtype=int64)

In [63]:
y_pred = model.predict(X_test)

NotFittedError: This GaussianNB instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.