In [1]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from autocorrect import Speller
from spellchecker import SpellChecker
import time
from datetime import datetime 
import spacy
from textblob import TextBlob

In [2]:
ttw = pd.read_csv('trainTwitter.csv')
ttw.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [3]:
for i in range(20):
    print(ttw['tweet'][i])

 @user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction.   #run
@user @user thanks for #lyft credit i can't use cause they don't offer wheelchair vans in pdx.    #disapointed #getthanked
  bihday your majesty
#model   i love u take with u all the time in urð±!!! ððððð¦ð¦ð¦
 factsguide: society now    #motivation
[2/2] huge fan fare and big talking before they leave. chaos and pay disputes when they get there. #allshowandnogo
 @user camping tomorrow @user @user @user @user @user @user @user dannyâ¦
the next school year is the year for exams.ð¯ can't think about that ð­ #school #exams   #hate #imagine #actorslife #revolutionschool #girl
we won!!! love the land!!! #allin #cavs #champions #cleveland #clevelandcavaliers  â¦
 @user @user welcome here !  i'm   it's so #gr8 !
 â #ireland consumer price index (mom) climbed from previous 0.2% to 0.5% in may   #blog #silver #gold #forex
we are so selfish. #orlando #standwithorlando #pulseshooting #orlandoshooting #biggerproblems #selfish #heabreaking   #values #love #
i get to see my daddy today!!   #80days #gettingfed
@user #cnn calls #michigan middle school 'build the wall' chant '' #tcot
no comment!  in #australia   #opkillingbay #seashepherd #helpcovedolphins #thecove  #helpcovedolphins
ouch...junior is angryð#got7 #junior #yugyoem   #omg
i am thankful for having a paner. #thankful #positive
retweet if you agree!
its #friday! ð smiles all around via ig user: @user #cookies make people
as we all know, essential oils are not made of chemicals.

In [4]:
start_time = datetime.now() 

stop_words = set(stopwords.words('english'))

ttw2 = ttw.copy()
ttw2['tweet'] = ttw2['tweet'].str.lower()
ttw2['tweet'] = ttw2['tweet'].str.replace(r'(\s)#\w+','') 
ttw2['tweet'] = ttw2['tweet'].str.replace('[^\w\s]','') 
ttw2['tweet'] = ttw2['tweet'].str.replace('[^a-z ]','') 
ttw2['tweet'] = ttw2['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stop_words))
print('Time elapsed in (hh:mm:ss.ms): "{}"'.format(datetime.now() - start_time))


ttw2.head(20)

Time elapsed in (hh:mm:ss.ms): "0:00:00.512728"

    id  label                                              tweet
0    1      0  user father dysfunctional selfish drags kids d...
1    2      0  user user thanks credit cant use cause dont of...
2    3      0                                     bihday majesty
3    4      0                        model love u take u time ur
4    5      0                                 factsguide society
5    6      0  huge fan fare big talking leave chaos pay disp...
6    7      0  user camping tomorrow user user user user user...
7    8      0             next school year year exams cant think
8    9      0                                          love land
9   10      0                               user user welcome im
10  11      0      consumer price index mom climbed previous may
11  12      0                                            selfish
12  13      0                                get see daddy today
13  14      1          user calls middle school build wall chant
14  15      1                                            comment
15  16      0                                ouchjunior angrygot
16  17      0                                     thankful paner
17  18      1                                      retweet agree
18  19      0         smiles around via ig user user make people
19  20      0                 know essential oils made chemicals

In [5]:
for i in range(20):
    print(ttw2['tweet'][i])

user father dysfunctional selfish drags kids dysfunction
user user thanks credit cant use cause dont offer wheelchair vans pdx
bihday majesty
model love u take u time ur
factsguide society
huge fan fare big talking leave chaos pay disputes get
user camping tomorrow user user user user user user user danny
next school year year exams cant think
love land
user user welcome im
consumer price index mom climbed previous may
selfish
get see daddy today
user calls middle school build wall chant
comment
ouchjunior angrygot
thankful paner
retweet agree
smiles around via ig user user make people
know essential oils made chemicals

In [6]:
#SPELLING

start_time = datetime.now() 

spell = Speller(lang='en')

for i in range(len(ttw2['tweet'])):
    querywords = ttw2['tweet'][i].split()
    words_after_speller = [spell(word) for word in querywords]
    ttw2['tweet'][i] = ' '.join(words_after_speller)


print('Time elapsed in (hh:mm:ss.ms): "{}"'.format(datetime.now() - start_time))
ttw2.to_csv('ttw2_finalSpell.csv', index=False)
#Time elapsed in (hh:mm:ss.ms): "2:49:43.108707"
#Time elapsed in (hh:mm:ss.ms): "0:39:32.493799"

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

Time elapsed in (hh:mm:ss.ms): "0:39:32.493799"