In [1]:
import pandas as pd
import re
import requests
from nltk.util import bigrams

import time
from datetime import datetime 

start_time = datetime.now()

In [2]:
df = pd.read_csv('final_520.csv')
df

,mdd,t_depth,NN,VB,JJ,PREPOSITION,DEF,CONJ,BN,NNP,...,RB,CC,AT,QW,REL,PRP,IN,DTT,DT,MD
0,3.75,4,4,0,0,2,2,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,14.82,34,16,6,8,14,4,6,4,6,...,2,2,0,0,0,0,0,0,0,0
2,14.41,28,12,4,2,2,12,4,4,4,...,0,2,2,2,2,4,2,0,0,0
3,18.42,36,16,6,4,8,20,0,0,6,...,2,2,2,0,2,0,4,2,0,0
4,19.70,43,16,2,8,6,28,2,0,14,...,0,0,0,2,4,2,0,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,16.91,33,14,4,2,4,12,0,6,2,...,0,0,2,0,8,2,6,0,0,0
517,7.17,15,10,2,2,8,10,0,0,2,...,2,0,2,0,0,0,0,0,0,2
518,13.08,25,16,2,2,8,8,2,2,6,...,0,0,0,0,0,0,4,0,0,2
519,5.27,12,6,2,0,4,6,0,0,2,...,0,0,2,0,0,0,0,0,0,2
520,12.22,23,8,2,2,4,8,2,4,0,...,0,0,0,2,2,2,2,0,0,2

In [3]:
df2 = pd.read_csv('sentences_final4.csv')
df2

                                              sentence  no_change  summarizing
0                                    והנפיחות בעיניים?          1            0
1    ככלל, כדאי להיות קשובים לגוף וכשאשר מופיעים סי...          0            1
2    הצגה עצמיתתחילה תתבקש לפרט את המחלות או הליקוי...          0            1
3    מגמת משרד החינוך הינה לשלב את הילד בעל הצרכים ...          0            1
4    בייעוץ כזה יובאו בחשבון המסלול, משך הטיול, אופ...          0            1
..                                                 ...        ...          ...
516  הורים יקרים,במדריך הזה מפורט התהליך העומד בפני...          0            1
517  מהיום ניתן לקבל  את חשבון הארנונה ישירות לדואר...          0            1
518  .תורם לאיכות הסביבה, קבלת חשבון ארנונה תקופתי ...          0            1
519      ניתן לקבל את חשבון הארנונה למייל במילוי טופס.          0            1
520  חשבון הארנונה בדואר האלקטרוני מגיע כשהוא מאובט...          0            1

[521 rows x 3 columns]

In [4]:

words = []
letters = []
word_avg = []
numbers = []
symbols = []
if_question = []

punctuation = []
sym_hashtag = []
sym_shtrudel = []
sym_dollar = []
sym_ampersand = []
sym_percend = []
sym_star = []
sym_tilda = []
sym_math = []
sym_logic = []
sym_brackets = []
sym_num = []
sym_quotes = []
sym_slashes = []
bigrams = []

In [5]:
for s in df2.sentence:
    
    bigrams.append(len(s.split())-1)
    
    val = re.findall(r'\w+', s)
    words.append(len(val))
    
    val = re.findall(r'\w', s)
    letters.append(len(val))
    
    val = re.findall(r'\w+', s)
    average = sum(len(word) for word in val) / len(val)
    word_avg.append(round(average, 3))
    
    val = re.findall(r'[0-9]', s)
    numbers.append(len(val))
    
    val = re.findall(r'[^א-ת0-9 ]', s)
    symbols.append(len(val))
    
    val = re.findall(r'[`!^:;\',.?]', s)
    punctuation.append(len(val))
    
    val = re.findall(r'[#]', s)
    sym_hashtag.append(len(val))
    
    val = re.findall(r'[@]', s)
    sym_shtrudel.append(len(val))
    
    val = re.findall(r'[$]', s)
    sym_dollar.append(len(val))
    
    val = re.findall(r'[&]', s)
    sym_ampersand.append(len(val))
    
    val = re.findall(r'[%]', s)
    sym_percend.append(len(val))
    
    val = re.findall(r'[*]', s)
    sym_star.append(len(val))
    
    val = re.findall(r'[~]', s)
    sym_tilda.append(len(val))
    
    val = re.findall(r'[\+\-\*\/<>=%^]', s)
    sym_math.append(len(val))
    
    val = re.findall(r'[&|]', s)
    sym_logic.append(len(val))
    
    val = re.findall(r'[()[]{}]', s)
    sym_brackets.append(len(val))
    
    val = re.findall(r'[№]', s)
    sym_num.append(len(val))
    
    val = re.findall(r'["\']', s)
    sym_quotes.append(len(val))
    
    val = re.findall(r'[\//]', s)
    sym_slashes.append(len(val))
    
    if s[len(s)-1]=='?':
        if_question.append(1)
    else:
        if_question.append(0)
        
print('Time elapsed in (hh:mm:ss.ms): "{}"'.format(datetime.now() - start_time))

Time elapsed in (hh:mm:ss.ms): "0:00:00.073266"

In [6]:
df3 = pd.DataFrame({'sentence' : df2.sentence,
                    'mdd' : df.mdd,
                    't_depth' : df.t_depth,
                    'no_change' : df2.no_change,
                    'summarizing' : df2.summarizing,
                    'bigrams' : bigrams,
                    'words': words, 
                    'letters': letters, 
                    'word_avg': word_avg,
                    'numbers': numbers, 
                    'symbols': symbols,
                    'if_question': if_question,
                    'punctuation': punctuation,
                    'sym_hashtag': sym_hashtag,
                    'sym_shtrudel': sym_shtrudel,
                    'sym_dollar': sym_dollar,
                    'sym_ampersand': sym_ampersand,
                    'sym_percend': sym_percend,
                    'sym_star': sym_star,
                    'sym_tilda': sym_tilda,
                    'sym_math': sym_math,
                    'sym_logic': sym_logic,
                    'sym_brackets': sym_brackets,
                    'sym_num': sym_num,
                    'sym_quotes': sym_quotes,
                    'sym_slashes': sym_slashes,
                    'NN' : df.NN,
                    'VB' : df.VB,
                    'JJ' : df.JJ,
                    'PREPOSITION' : df.PREPOSITION,
                    'DEF' : df.DEF,
                    'CONJ' : df.CONJ,
                    'BN' : df.BN,
                    'NNP' : df.NNP,
                    'NNT' : df.NNT,
                    'TEMP' : df.TEMP,
                    'RB' : df.RB,
                    'CC' : df.CC,
                    'AT' : df.AT,
                    'QW' : df.QW,
                    'REL' : df.REL,
                    'PRP' : df.PRP,
                    'IN' : df.IN,
                    'DTT' : df.DTT,
                    'DT' : df.DT,
                    'MD' : df.MD})

df3.head()

,sentence,mdd,t_depth,no_change,summarizing,bigrams,words,letters,word_avg,numbers,...,RB,CC,AT,QW,REL,PRP,IN,DTT,DT,MD
0,והנפיחות בעיניים?,3.75,4,1,0,1,2,15,7.500,0,...,0,0,0,0,0,0,0,0,0,0
1,"ככלל, כדאי להיות קשובים לגוף וכשאשר מופיעים סי...",14.82,34,0,1,25,25,130,5.200,0,...,2,2,0,0,0,0,0,0,0,0
2,הצגה עצמיתתחילה תתבקש לפרט את המחלות או הליקוי...,14.41,28,0,1,19,21,99,4.714,0,...,0,2,2,2,2,4,2,0,0,0
3,מגמת משרד החינוך הינה לשלב את הילד בעל הצרכים ...,18.42,36,0,1,25,26,126,4.846,0,...,2,2,2,0,2,0,4,2,0,0
4,"בייעוץ כזה יובאו בחשבון המסלול, משך הטיול, אופ...",19.70,43,0,1,24,24,139,5.792,0,...,0,0,0,2,4,2,0,2,2,0

In [7]:
df3.shape

(521, 46)

In [8]:
df3.to_csv('sentences_521_features_46.csv', index = False, encoding='utf-8-sig')